import main
print('##perhitungan luas persegi##')
main. l_persegi(10)
print('##perhitungan luas persegi panjang##')
main. l_persegi_panjang(5,3)
print('##perhitungan luas seegitiga##')
main. l_segitiga(5,10)
print('##perhitungan luas lingkaran##')
main. l_lingkaran(20)
print('##perhitungan luas layang layang##')
main. l_layang_layang(7,15)